name: recipe_book
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Peticiones HTTP
  http: ^1.6.0

  # Manejo de estado
  provider: ^6.1.5+1

  # Localización
  flutter_localizations:
    sdk: flutter

  intl: 0.20.2

  cupertino_icons: ^1.0.8

  # Iconos modernos
  iconsax: ^0.0.8
  shared_preferences: ^2.5.4

  # Tipografía y SVG
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  
  # UI Pro y Animaciones
  flutter_animate: ^4.5.0
  slide_to_act: ^2.0.2

  image_picker: ^1.2.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/